### ISSUE TITLE
Long Names cross onto other fields making it hard to read.

### ISSUE THREAD

**Issue by MrTreev** [Blooperly/orpheus-manager#2]
![caporph1](https://user-images.githubusercontent.com/16656570/31121776-49488662-a885-11e7-901a-27dfd72ce7ca.PNG)

**Comment by Blooperly** [comment]
I have a solution for this problem, but I will probably implement it after 1.0 release. For now abbreviations are your friend.

**Comment by Blooperly** [comment]
I no longer remember what my solution was, but I will still fix this eventually.
